name: deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Denoflare
        run: >
          deno install --unstable --allow-read --allow-net --allow-env --allow-run --name denoflare --force 
          https://raw.githubusercontent.com/skymethod/denoflare/v0.5.2/cli/cli.ts

      - name: Deploy
        run: denoflare push mobius --account-id ${{ secrets.ACCOUNT_ID }} --api_token ${{ secrets.API_TOKEN }}
